templates =[
    {'name': "harold",  'link': "harold"},
    {'name': "keanu",  'link': "keanu"},
    {'name': "ugandanknuck",  'link': "ugandanknuck"},
    {'name': "stonks",  'link': "stonks"},
    {'name': "spiderman",  'link': "spiderman"},
    {'name': "saltbae",  'link': "saltbae"},
    {'name': "smarter",  'link': "rollsafe"},
    {'name': "mini-keanu",'link': "mini-keanu"},
    {'name': "sparta",  'link': "sparta"},
    {'name': "aliens",  'link': "aag"},
    {'name': "buzz",  'link': "buzz"},
    {'name': "captain-america",  'link': "captain-america"},
    {'name': "changeMyMind",  'link': "cmm"},
    {'name': "girlPassing",  'link': "db"},
    {'name': "disastergirl",  'link': "disastergirl"},
    {'name': "drake",  'link': "drake"},
    {'name': "cantChose",  'link': "ds"},
    {'name': "facepalm",  'link': "facepalm"},
    {'name': "feelsgood",  'link': "feelsgood"},
    {'name': "inHell",  'link': "fine"},
    {'name': "fry",  'link': "fry"},
    {'name': "smarter",  'link': "gb"},
    {'name': "plan",  'link': "gru"},
    {'name': "happening",  'link': "happening"},
    {'name': "dogInPc",  'link': "noidea"},
    {'name': "michael-scott",  'link': "michael-scott"},
    {'name': "wtfMonkey",  'link': "persian"},
    {'name': "isThis",  'link': "pigeon"},
]